// <auto-generated />
using ConsultantRuleConstructor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultantRuleConstructor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RuleId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Refuse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuideId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("resettlementStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Document", b =>
                {
                    b.HasOne("ConsultantRuleConstructor.Entities.Profile", null)
                        .WithMany("requiredDocuments")
                        .HasForeignKey("ProfileId");

                    b.HasOne("ConsultantRuleConstructor.Entities.Rule", null)
                        .WithMany("Documents")
                        .HasForeignKey("RuleId");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Guide", b =>
                {
                    b.HasOne("ConsultantRuleConstructor.Entities.Rule", null)
                        .WithMany("Guids")
                        .HasForeignKey("RuleId");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Organization", b =>
                {
                    b.HasOne("ConsultantRuleConstructor.Entities.Guide", null)
                        .WithMany("Organizations")
                        .HasForeignKey("GuideId");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Profile", b =>
                {
                    b.HasOne("ConsultantRuleConstructor.Entities.Rule", null)
                        .WithMany("profiles")
                        .HasForeignKey("RuleId");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Guide", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Profile", b =>
                {
                    b.Navigation("requiredDocuments");
                });

            modelBuilder.Entity("ConsultantRuleConstructor.Entities.Rule", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Guids");

                    b.Navigation("profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
